name: db_test_coverage
description: A command-line tool that run tests with coverage on a project.
version: 0.1.1
homepage: https://github.com/bitsydarel/db_test_coverage

environment:
  sdk: '>=2.13.4 <3.0.0'

dependencies:
  args: ^2.1.1
  io: ^1.0.3
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  flutter_code_style: ^2.1.0
  test: ^1.17.10

executables:
  test_coverage:
